#!/usr/bin/env python3

"""Snakemake popgen demo pipeline

AUTHORS:
    A. Biddanda

A simple demo starter repo for popgen simulations.
"""

import pathlib
from snakemake.utils import validate


# reference the config file
configfile: "config/config.yaml"


# validate(config, schema="schemas/config.schema.yaml")

# configure shell behavior for all rules
shell.executable("/bin/bash")
shell.prefix("set -euo pipefail;")

# Create a log directory
pathlib.Path("logs/").mkdir(parents=True, exist_ok=True)


localrules:
    all,


rule all:
    input:
        "results/full_simulations.tsv",


include: "rules/sims.smk"
