executor: cluster-generic
cluster-generic-submit-cmd:
  mkdir -p logs/{rule} &&
  sbatch
    --partition={resources.partition}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --job-name=smk-{rule}-{wildcards}
    --account={resources.account}
    --output=logs/{rule}/{rule}-{wildcards}-%j.out
    --parsable
default-resources:
  - partition="parallel"
  - account="rmccoy22-condo"
  - mem_mb=1000
restart-times: 1
max-jobs-per-second: 5
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
jobs: 300
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True
